# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeSensors' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeSensors

  target 'NativeSensorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NativeSensors-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeSensors-tvOS

  target 'NativeSensors-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
